/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_db.JPanelModel;

import DAO.dbConnect;
import Service.IKhachHangService;
import Service.ISanPhamService;
import Service.KhachHangService;
import Service.SanPhamService;
import controller.QLGHController;
import controller.QLHDController;
import controller.QLSPController;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.DateTimeAtCompleted;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.GioHang;
import model.HoaDon;
import model.KhachHang;
import model.SanPham;
import test_db.JFrameModel.GioHangJFrameAddSP;
import test_db.JFrameModel.JFrameKHChoose;
import test_db.JFrameModel.KhachHangJFrame;
import test_db.JPanelModel.bill.TrangThaiThanhToan;
import test_db.JPanelModel.cthd.ChiTietHoaDonDto;
import test_db.JPanelModel.cthd.CthdManager;
import test_db.LoginJFrame;
import ubility.ClassTableHoaDon;

/**
 *
 * @author Minh Hoanfg
 */
public class GioHangJPanel extends javax.swing.JPanel {

    private ISanPhamService iSanPhamService = null;
    private IKhachHangService iKhachHangService = null;
    private int idRow = -1;
    private int inDex = -1;
    private QLSPController controller;
    private static List<GioHang> listGH = new ArrayList<>();
    private static List<KhachHang> listKH = new ArrayList<>();
    private static List<HoaDon> listHDC = new ArrayList<>();
    private static List<SanPham> listSP = new ArrayList<>();
    private JFrameKHChoose kHChoose;
    private QLGHController qlghc;
    private QLHDController hdchoController;
    private LoginJFrame ljf;
    private static int[] idCheck = new int[100];

    /**
     * Creates new form GioHangJPanel
     */
    public GioHangJPanel() {
        initComponents();
        setEnableBtn();
        controller = new QLSPController(jpnviewtb, jtftimkiem);
        controller.setDataModelGioHang();
        this.iSanPhamService = new SanPhamService();
        this.iKhachHangService = new KhachHangService();
        listKH = iKhachHangService.getList();
        listSP = iSanPhamService.listSPService();
        qlghc = new QLGHController(jpngiohang);
        qlghc.setDataModel(listGH);
        kHChoose = new JFrameKHChoose(jlblmkh, jlbltenkh);
        ljf = new LoginJFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnttsanpham = new javax.swing.JPanel();
        jtftimkiem = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jpnviewtb = new javax.swing.JPanel();
        btnthemsp = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnchonkh = new javax.swing.JButton();
        jlblmkh = new javax.swing.JLabel();
        jlbltenkh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnthanhtoan = new javax.swing.JButton();
        btnhuyhd = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        jtfghichu = new javax.swing.JTextField();
        jlblmhd = new javax.swing.JLabel();
        jlbltongtien = new javax.swing.JLabel();
        jlblthanhtoan = new javax.swing.JLabel();
        jlbltienthua = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcbhttt = new javax.swing.JComboBox<>();
        jcbhtgh = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtftienkhachdua = new javax.swing.JTextField();
        btntaohoadon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jpngiohang = new javax.swing.JPanel();
        btnxoasp = new javax.swing.JButton();
        btnxoaall = new javax.swing.JButton();
        btnfixsl = new javax.swing.JButton();
        jpnhdcho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblnvlogin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 51));

        jpnttsanpham.setBackground(new java.awt.Color(255, 204, 51));
        jpnttsanpham.setBorder(javax.swing.BorderFactory.createTitledBorder("Các sản phẩm hiện có"));

        jLabel29.setText("Search :");

        jpnviewtb.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jpnviewtbLayout = new javax.swing.GroupLayout(jpnviewtb);
        jpnviewtb.setLayout(jpnviewtbLayout);
        jpnviewtbLayout.setHorizontalGroup(
            jpnviewtbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnviewtbLayout.setVerticalGroup(
            jpnviewtbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        btnthemsp.setBackground(new java.awt.Color(255, 204, 51));
        btnthemsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/plus_1.png"))); // NOI18N
        btnthemsp.setText("Thêm sản phẩm");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnttsanphamLayout = new javax.swing.GroupLayout(jpnttsanpham);
        jpnttsanpham.setLayout(jpnttsanphamLayout);
        jpnttsanphamLayout.setHorizontalGroup(
            jpnttsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnttsanphamLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(btnthemsp)
                .addGap(115, 115, 115)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtftimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jpnttsanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnviewtb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnttsanphamLayout.setVerticalGroup(
            jpnttsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnttsanphamLayout.createSequentialGroup()
                .addGroup(jpnttsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(btnthemsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnviewtb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 204, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBackground(new java.awt.Color(255, 204, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Mã khách hàng :");

        jLabel6.setText("Tên khách hàng :");

        btnchonkh.setBackground(new java.awt.Color(255, 204, 51));
        btnchonkh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/tap.png"))); // NOI18N
        btnchonkh.setText("Chọn");
        btnchonkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonkhActionPerformed(evt);
            }
        });

        jlblmkh.setText("none");

        jlbltenkh.setText("none");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblmkh, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jlbltenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnchonkh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchonkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlblmkh))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlbltenkh))))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Hóa đơn số :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tổng tiền :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Giảm giá :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Thanh toán :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Tiền khách đưa");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tiền thừa :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Hình thức thanh toán :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Hình thức mua hàng :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Ghi chú :");

        btnthanhtoan.setBackground(new java.awt.Color(255, 204, 51));
        btnthanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/pay.png"))); // NOI18N
        btnthanhtoan.setText("THANH TOÁN");
        btnthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoanActionPerformed(evt);
            }
        });

        btnhuyhd.setBackground(new java.awt.Color(255, 204, 51));
        btnhuyhd.setText("Hủy hóa đơn");

        btnlammoi.setBackground(new java.awt.Color(255, 204, 51));
        btnlammoi.setText("Làm mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        jlblmhd.setText("0");

        jlbltongtien.setText("0.0");

        jlblthanhtoan.setText("0.0");

        jlbltienthua.setText("0.0");

        jLabel20.setText("0.0");

        jcbhttt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ", "Chuyển khoản" }));

        jcbhtgh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trực tiếp", "Giao hàng" }));

        jLabel24.setText("VND");

        jLabel25.setText("VND");

        jLabel26.setText("VND");

        jLabel27.setText("VND");

        jLabel28.setText("VND");

        jtftienkhachdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftienkhachduaActionPerformed(evt);
            }
        });

        btntaohoadon.setBackground(new java.awt.Color(255, 204, 51));
        btntaohoadon.setText("Tạo hóa đơn");
        btntaohoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaohoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbhttt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbhtgh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlbltongtien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlblthanhtoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlbltienthua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jtftienkhachdua)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlblmhd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntaohoadon)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfghichu)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnthanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnhuyhd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblmhd)
                    .addComponent(btntaohoadon))
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbltongtien)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblthanhtoan)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbltienthua)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbhttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhtgh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhuyhd)
                    .addComponent(btnlammoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Chi tiết đơn hàng");

        jPanel11.setBackground(new java.awt.Color(255, 204, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));

        jpngiohang.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jpngiohangLayout = new javax.swing.GroupLayout(jpngiohang);
        jpngiohang.setLayout(jpngiohangLayout);
        jpngiohangLayout.setHorizontalGroup(
            jpngiohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        jpngiohangLayout.setVerticalGroup(
            jpngiohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        btnxoasp.setBackground(new java.awt.Color(255, 204, 51));
        btnxoasp.setText("Xóa sản phẩm");
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });

        btnxoaall.setBackground(new java.awt.Color(255, 204, 51));
        btnxoaall.setText("Xóa tất cả");
        btnxoaall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaallActionPerformed(evt);
            }
        });

        btnfixsl.setBackground(new java.awt.Color(255, 204, 51));
        btnfixsl.setText("Sửa số lượng");
        btnfixsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfixslActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpngiohang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnfixsl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoaall, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoasp)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnxoaall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoasp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfixsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jpngiohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnhdcho.setBackground(new java.awt.Color(255, 204, 51));
        jpnhdcho.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn chờ"));

        javax.swing.GroupLayout jpnhdchoLayout = new javax.swing.GroupLayout(jpnhdcho);
        jpnhdcho.setLayout(jpnhdchoLayout);
        jpnhdchoLayout.setHorizontalGroup(
            jpnhdchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        jpnhdchoLayout.setVerticalGroup(
            jpnhdchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Nhân viên :");

        jlblnvlogin.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnttsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnhdcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblnvlogin)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblnvlogin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnhdcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnttsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setEnableBtn() {
        jlblnvlogin.setText(String.valueOf(ljf.nhanVien.getTenNV()));
        btnfixsl.setEnabled(false);
        btnthanhtoan.setEnabled(false);
        btnthemsp.setEnabled(false);
        btnxoaall.setEnabled(false);
        btnxoasp.setEnabled(false);
        btnlammoi.setEnabled(false);
        btnhuyhd.setEnabled(false);
    }

    public void setVisible() {
        btnthanhtoan.setEnabled(true);
        btnthemsp.setEnabled(true);
        btnlammoi.setEnabled(true);
        btnhuyhd.setEnabled(true);
        btnxoaall.setEnabled(true);
        btnxoasp.setEnabled(true);
        btnfixsl.setEnabled(true);
    }

    public void setViewKH(int i) {
        System.out.println(listKH.get(i).getMaKH());
        jlblmkh.setText("01");
        jlblmkh.setText(listKH.get(i).getMaKH());
        jlbltenkh.setText("hoang");
    }

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        idRow = controller.getIndex();
        GioHang gh = new GioHang();
        if (idRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm ");
        } else {
            if (idCheck[idRow] == 0) {
//                List<SanPham> listSP = iSanPhamService.listSPService();
                gh.setmSP(listSP.get(idRow).getMaSP());
                gh.settSP(listSP.get(idRow).getTenSP());
                gh.setDonGiaSP(listSP.get(idRow).getGiaSP());
                listGH.add(gh);
                GioHangJFrameAddSP frameAddSP = new GioHangJFrameAddSP(gh, listGH, jpngiohang, jlbltongtien, jlblthanhtoan);
                frameAddSP.setResizable(false);
                frameAddSP.setLocationRelativeTo(null);
                frameAddSP.setVisible(true);
                frameAddSP.setIndex(idRow);
                idCheck[idRow] = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Sản phẩm đã được thêm");
            }
        }
    }//GEN-LAST:event_btnthemspActionPerformed

    private void jtftienkhachduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftienkhachduaActionPerformed
        if (Float.valueOf(jtftienkhachdua.getText()) >= Float.valueOf(jlblthanhtoan.getText())) {
            jlbltienthua.setText(String.valueOf(Double.valueOf(jtftienkhachdua.getText()) - Double.valueOf(jlbltongtien.getText())));
        } else {
            JOptionPane.showMessageDialog(jtftienkhachdua, "Số tiền phải lớn hơn tiền thanh toán !");
        }
    }//GEN-LAST:event_jtftienkhachduaActionPerformed

    private void btnchonkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonkhActionPerformed
//        kHChoose = new JFrameKHChoose();
        kHChoose.setResizable(false);
        kHChoose.setLocationRelativeTo(null);
        kHChoose.setVisible(true);
    }//GEN-LAST:event_btnchonkhActionPerformed

    public void tongtien(List<GioHang> listGH) {
        double total = 0;
        for (int i = 0; i < listGH.size(); i++) {
            total = total + (Double.parseDouble(listGH.get(i).getDonGiaSP()) * listGH.get(i).getSlSP());
        }
        jlbltongtien.setText(String.valueOf(total));
        jlblthanhtoan.setText(String.valueOf(total));
    }
    
    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        if (listGH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm trong giỏ hàng !");
        } else {
            int choice = JOptionPane.showConfirmDialog(btnxoasp, "Bạn có chắc chắn xóa sản phẩm này ?", "",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choice == 0) {
                inDex = qlghc.getIndex();
                System.out.println(inDex);
                for (int i = 0; i < listSP.size(); i++) {
                    if (listGH.get(inDex).getmSP() == listSP.get(i).getMaSP()) {
                        System.out.println("delete = " + i);
                        idCheck[i] = 0;
                    }
                }
                listGH.remove(inDex);
                qlghc.setDataModel(listGH);
                tongtien(listGH);
            }
        }
    }//GEN-LAST:event_btnxoaspActionPerformed

    private void btnxoaallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaallActionPerformed
        if (listGH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm trong giỏ hàng !");
        } else {
            int choice = JOptionPane.showConfirmDialog(btnxoasp, "Bạn có chắc chắn xóa tất cả sản phẩm ?", "",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choice == 0) {
                listGH.removeAll(listGH);
                qlghc.setDataModel(listGH);
                for (int i = 0; i < listSP.size(); i++) {
                    idCheck[i] = 0;
                }
                tongtien(listGH);
            }
        }
    }//GEN-LAST:event_btnxoaallActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        int choice = JOptionPane.showConfirmDialog(btnxoasp, "Bạn có chắc chắn làm mới giỏ hàng ?", "",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == 0) {
            listGH.removeAll(listGH);
            jlbltongtien.setText("0.0");
            jlblthanhtoan.setText("0.0");
            jtftienkhachdua.setText("");
        }
    }//GEN-LAST:event_btnlammoiActionPerformed

    private void btnfixslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfixslActionPerformed

    }//GEN-LAST:event_btnfixslActionPerformed

    private void btntaohoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaohoadonActionPerformed
        hdchoController = new QLHDController(jpnhdcho, null);
        System.out.println(hdchoController.getIndex());
        jlblmhd.setText(String.valueOf(Integer.valueOf(hdchoController.getIndex()) + 1));
        setDataModelHDcho();
        setVisible();
        btntaohoadon.setEnabled(false);
        btnchonkh.setVisible(false);
    }//GEN-LAST:event_btntaohoadonActionPerformed

    private String[] listColumnHDcho = {"Mã Hóa Đơn", "Mã khách hàng", "Mã nhân viên", "Ngày tạo"};

    private TableRowSorter<TableModel> rowSorter = null;

    public void setDataModelHDcho() {
//        List<HoaDon> listItem = iHoaDonService.getListHD();
        HoaDon hd = new HoaDon();
        hd.setMaHD(Integer.valueOf(jlblmhd.getText()));
        hd.setMaKH(Integer.valueOf(jlblmkh.getText()));
        hd.setMaNV(ljf.nhanVien.getMaNV());
        hd.setNgayTao(null);
        listHDC.add(hd);
        DefaultTableModel model = new ClassTableHoaDon().setTableHoaDonCho(listHDC, listColumnHDcho);

        JTable table = new JTable(model);
        rowSorter = new TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);

        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        table.getTableHeader().setPreferredSize(new Dimension(20, 20));
        table.setRowHeight(20);
        table.validate();
        table.repaint();

        JScrollPane scrollPane = new JScrollPane();
        scrollPane.getViewport().add(table);
        scrollPane.setPreferredSize(new Dimension(100, 100));

        jpnhdcho.removeAll();
        jpnhdcho.setLayout(new BorderLayout());
        jpnhdcho.add(scrollPane);
        jpnhdcho.validate();
        jpnhdcho.repaint();
    }

    private void btnthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoanActionPerformed
        try {
            Connection cons = (Connection) dbConnect.getConnection();
            String sql = "Insert into HOADON(MAHOADON, MAKHACHHANG, MANHANVIEN, NGAYTAO, TONGTIEN, THANHTOAN,"
                    + "FK_HINHTHUCGIAOHANG, FK_HINHTHUCTHANHTOAN, FK_TRANGTHAITHANHTOAN, GHICHU)Values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps;
            ps = cons.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);

            ps.setInt(1, hdchoController.getIndex() + 1);
            ps.setInt(2, Integer.valueOf(jlblmkh.getText()));
            ps.setInt(3, ljf.nhanVien.getMaNV());
            ps.setDate(4, Date.valueOf(LocalDate.now()));
            ps.setFloat(5, Float.valueOf(jlbltongtien.getText()));
            ps.setFloat(6, Float.valueOf(jlblthanhtoan.getText()));
            ps.setInt(7, jcbhtgh.getSelectedIndex() + 1);
            ps.setInt(8, jcbhttt.getSelectedIndex() + 1);
            ps.setInt(9, TrangThaiThanhToan.DaThanhToan);
            ps.setString(10, jtfghichu.getText());

            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();

            int generatedKey = 0;
            if (rs.next()) {
                generatedKey = rs.getInt(1);
            }
            ps.close();
            rs.close();
            cons.close();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            
            // tạo CTHD
            List<ChiTietHoaDonDto> listCTHD = new ArrayList<>();
            for(int i = 0; i < listGH.size(); i++){
                float giasp = Float.valueOf(listGH.get(i).getDonGiaSP()) * Float.valueOf(listGH.get(i).getSlSP());
                ChiTietHoaDonDto cthd = new ChiTietHoaDonDto(Integer.valueOf(jlblmhd.getText()),
                        Integer.valueOf(listGH.get(i).getmSP()), listGH.get(i).getSlSP(),
                        Float.valueOf(giasp),
                        jtfghichu.getText());
                listCTHD.add(cthd);
            }
            
            CthdManager.addChiTietHoaDon(listCTHD);

        } catch (SQLException ex) {
            Logger.getLogger(KhachHangJFrame.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthanhtoanActionPerformed

    //Getter and setter gobal_variable index
    public void setInDex(int i) {
        inDex = i;
    }

    public int getIndex() {
        return inDex;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchonkh;
    private javax.swing.JButton btnfixsl;
    private javax.swing.JButton btnhuyhd;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btntaohoadon;
    private javax.swing.JButton btnthanhtoan;
    private javax.swing.JButton btnthemsp;
    private javax.swing.JButton btnxoaall;
    private javax.swing.JButton btnxoasp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> jcbhtgh;
    private javax.swing.JComboBox<String> jcbhttt;
    private javax.swing.JLabel jlblmhd;
    private javax.swing.JLabel jlblmkh;
    private javax.swing.JLabel jlblnvlogin;
    private javax.swing.JLabel jlbltenkh;
    private javax.swing.JLabel jlblthanhtoan;
    private javax.swing.JLabel jlbltienthua;
    private javax.swing.JLabel jlbltongtien;
    private javax.swing.JPanel jpngiohang;
    private javax.swing.JPanel jpnhdcho;
    private javax.swing.JPanel jpnttsanpham;
    private javax.swing.JPanel jpnviewtb;
    private javax.swing.JTextField jtfghichu;
    private javax.swing.JTextField jtftienkhachdua;
    private javax.swing.JTextField jtftimkiem;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
