/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test_db;

import bean.DanhMuc;
import controller.Screens;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Minh Hoanfg
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setTitle("Cửa hàng điện thoại");
        
        Screens screens = new Screens(jpnView);
        screens.setView(jpnGH, jlblGH);
        
        List<DanhMuc> listItem = new ArrayList<>();
        listItem.add(new DanhMuc("KhachHang", jpnKH, jlblKH));
        listItem.add(new DanhMuc("GioHang", jpnGH, jlblGH));
        listItem.add(new DanhMuc("HoaDon", jpnHD, jlblHD));
        listItem.add(new DanhMuc("ThongKe", jpnTK, jlblTK));
        listItem.add(new DanhMuc("TroGiup", jpnTG, jlblTG));
        listItem.add(new DanhMuc("NhanVien", jpnNhanVien, jlblNhanVien));
        listItem.add(new DanhMuc("SanPham", jpnkhosp, jlblkhosp));
        screens.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnGH = new javax.swing.JPanel();
        jlblGH = new javax.swing.JLabel();
        jpnKH = new javax.swing.JPanel();
        jlblKH = new javax.swing.JLabel();
        jpnHD = new javax.swing.JPanel();
        jlblHD = new javax.swing.JLabel();
        jpnTK = new javax.swing.JPanel();
        jlblTK = new javax.swing.JLabel();
        jpnTG = new javax.swing.JPanel();
        jlblTG = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        jlblNhanVien = new javax.swing.JLabel();
        jpnkhosp = new javax.swing.JPanel();
        jlblkhosp = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setBackground(new java.awt.Color(255, 204, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/smartphone.png"))); // NOI18N
        jLabel1.setText("Cửa hàng điện thoại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnGH.setBackground(new java.awt.Color(255, 204, 51));
        jpnGH.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblGH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblGH.setForeground(new java.awt.Color(51, 51, 51));
        jlblGH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/shopping-cart.png"))); // NOI18N
        jlblGH.setText("Bán hàng");

        javax.swing.GroupLayout jpnGHLayout = new javax.swing.GroupLayout(jpnGH);
        jpnGH.setLayout(jpnGHLayout);
        jpnGHLayout.setHorizontalGroup(
            jpnGHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGHLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlblGH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnGHLayout.setVerticalGroup(
            jpnGHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnGHLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblGH)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnKH.setBackground(new java.awt.Color(255, 204, 51));

        jlblKH.setBackground(new java.awt.Color(204, 204, 204));
        jlblKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblKH.setForeground(new java.awt.Color(51, 51, 51));
        jlblKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/people.png"))); // NOI18N
        jlblKH.setText("Khách hàng");

        javax.swing.GroupLayout jpnKHLayout = new javax.swing.GroupLayout(jpnKH);
        jpnKH.setLayout(jpnKHLayout);
        jpnKHLayout.setHorizontalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jlblKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKHLayout.setVerticalGroup(
            jpnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblKH)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpnHD.setBackground(new java.awt.Color(255, 204, 51));
        jpnHD.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblHD.setForeground(new java.awt.Color(51, 51, 51));
        jlblHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/invoice.png"))); // NOI18N
        jlblHD.setText("Hóa đơn");

        javax.swing.GroupLayout jpnHDLayout = new javax.swing.GroupLayout(jpnHD);
        jpnHD.setLayout(jpnHDLayout);
        jpnHDLayout.setHorizontalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHDLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlblHD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHDLayout.setVerticalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHDLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblHD)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnTK.setBackground(new java.awt.Color(255, 204, 51));
        jpnTK.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblTK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTK.setForeground(new java.awt.Color(51, 51, 51));
        jlblTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/trend.png"))); // NOI18N
        jlblTK.setText("Thống kê");

        javax.swing.GroupLayout jpnTKLayout = new javax.swing.GroupLayout(jpnTK);
        jpnTK.setLayout(jpnTKLayout);
        jpnTKLayout.setHorizontalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTKLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlblTK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTKLayout.setVerticalGroup(
            jpnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTKLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblTK)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnTG.setBackground(new java.awt.Color(255, 204, 51));
        jpnTG.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblTG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblTG.setForeground(new java.awt.Color(51, 51, 51));
        jlblTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/exit.png"))); // NOI18N
        jlblTG.setText("Thoát");

        javax.swing.GroupLayout jpnTGLayout = new javax.swing.GroupLayout(jpnTG);
        jpnTG.setLayout(jpnTGLayout);
        jpnTGLayout.setHorizontalGroup(
            jpnTGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTGLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jlblTG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTGLayout.setVerticalGroup(
            jpnTGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblTG)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnNhanVien.setBackground(new java.awt.Color(255, 204, 51));
        jpnNhanVien.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblNhanVien.setForeground(new java.awt.Color(51, 51, 51));
        jlblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/teamwork.png"))); // NOI18N
        jlblNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
        jpnNhanVien.setLayout(jpnNhanVienLayout);
        jpnNhanVienLayout.setHorizontalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlblNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnNhanVienLayout.setVerticalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblNhanVien)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnkhosp.setBackground(new java.awt.Color(255, 204, 51));
        jpnkhosp.setPreferredSize(new java.awt.Dimension(258, 60));

        jlblkhosp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblkhosp.setForeground(new java.awt.Color(51, 51, 51));
        jlblkhosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/48x48/warehouse.png"))); // NOI18N
        jlblkhosp.setText("Kho sản phẩm");

        javax.swing.GroupLayout jpnkhospLayout = new javax.swing.GroupLayout(jpnkhosp);
        jpnkhosp.setLayout(jpnkhospLayout);
        jpnkhospLayout.setHorizontalGroup(
            jpnkhospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhospLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlblkhosp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnkhospLayout.setVerticalGroup(
            jpnkhospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhospLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblkhosp)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jpnGH, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jpnKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jpnTG, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(jpnkhosp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnGH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnkhosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jpnTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnView.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame newJFrame = new NewJFrame();
                newJFrame.setResizable(false);
                newJFrame.setLocationRelativeTo(null);
                newJFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlblGH;
    private javax.swing.JLabel jlblHD;
    private javax.swing.JLabel jlblKH;
    private javax.swing.JLabel jlblNhanVien;
    private javax.swing.JLabel jlblTG;
    private javax.swing.JLabel jlblTK;
    private javax.swing.JLabel jlblkhosp;
    private javax.swing.JPanel jpnGH;
    private javax.swing.JPanel jpnHD;
    private javax.swing.JPanel jpnKH;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnTG;
    private javax.swing.JPanel jpnTK;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnkhosp;
    // End of variables declaration//GEN-END:variables
}
